function scr_initinput3() //gml_Script_scr_initinput2
{
    ini_open("saveData.ini")
    global.key_upV = ini_read_string("ControlsKeys=", "up", keyboard_check(ord("i")))
    global.key_rightV = ini_read_string("ControlsKeys3", "right", keyboard_check(ord("l")))
    global.key_leftV = ini_read_string("ControlsKeys3", "left", keyboard_check(ord("k")))
    global.key_downV = ini_read_string("ControlsKeys3", "down", keyboard_check(ord("j")))
    global.key_jumpV = ini_read_string("ControlsKeys3", "jump", vk_numpad4 )
    global.key_slapV = ini_read_string("ControlsKeys3", "slap", vk_numpad6 )
    global.key_tauntV = ini_read_string("ControlsKeys3", "taunt", vk_numpad9)
    global.key_shootV = ini_read_string("ControlsKeys3", "shoot", vk_numpad2 )
    global.key_attackV = ini_read_string("ControlsKeys3", "attack", vk_numpad6)
    global.key_startV = ini_read_string("ControlsKeys3", "start", 80)
    global.key_chainsawV = ini_read_string("ControlsKeys", "chainsaw", 77)
    global.key_upCV = ini_read_string("ControllerButton", "up", 32781)
    global.key_rightCV = ini_read_string("ControllerButton", "right", 32784)
    global.key_leftCV = ini_read_string("ControllerButton", "left", 32783)
    global.key_downCV = ini_read_string("ControllerButton", "down", 32782)
    global.key_jumpCV = ini_read_string("ControllerButton", "jump", 32769)
    global.key_slapCV = ini_read_string("ControllerButton", "slap", 32771)
    global.key_tauntCV = ini_read_string("ControllerButton", "taunt", 32772)
    global.key_shootCV = ini_read_string("ControllerButton", "shoot", 32770)
    global.key_attackCV = ini_read_string("ControllerButton", "attack", 32774)
    global.key_startCV = ini_read_string("ControllerButton", "start", 32778)
    global.key_chainsawCV = ini_read_string("ControlsKeys", "chainsaw", 32773)
    ini_close()
}

